[tool.poetry]
name = "fastapi-toolforge-blueprint"
version = "0.1.0"
description = "Sample FastAPI app based on the official tutorial. Configured for deployment on Toolforge."
authors = ["Slavina Stefanova <me@slavina.dev>"]
readme = "README.md"
packages = [{include = "fastapi_toolforge_blueprint"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.1"
uvicorn = "^0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
